### ISSUE TITLE
GUI checklist

### ISSUE THREAD

**Issue by jpcima** [jpcima/DelayArchitect#1]
- [ ] main screen top row with toggle buttons
- [x] main screen bottom row with intervals
- [ ] value tooltips
- [x] tap multiple selection and highlighting
- [x] lasso selection
- [x] mini map
- [x] values as bars on mini map
- [ ] auto zoom
- [x] full range switch when tapping, and restore
- [x] appearance of taps when several overlap
- [ ] tap slider for width
- [ ] saving and recalling UI state
- [x] tapping should not cycle around
- [x] alignment of taps to grid (the UI logic)
- [x] display the low dB slider value as "-inf dB"
- [x] icons for small buttons (flip, mute, enable, etc...)
- [x] add "flip" button
- [x] reference horizontal for zero gain, pan center, etc..
- [ ] inverted slider for pan on main screen
- [x] mouse-wheelable combo boxes
- [ ] tap sliders snap on round values
- [x] indicator labels of time range min and max
- [x] click on intervals row to add tap
- [x] edit LNF such that combo-box centered text is centered based on the full-width

maybe
- [x] tapping for the first time clears existing taps
- [x] tapping resets the parameters of the new tap to defaults
